version: '3'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
# custom_networks_here

services:

  # MQTT-Broker
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./volumes/mosquitto/config:/mosquitto/config
    logging:
      options:
        max-size: "5m"
        max-file: "3"
      
  # startpage for ei23-SmartHomeServer
  # ei23:
  #   image: nginx:alpine
  #   container_name: ei23
  #   volumes:
  #     - ./volumes/ei23/conf:/etc/nginx/conf.d
  #     - ./volumes/ei23/web:/www
  #     - ./volumes/ei23/docs/site:/www/docs
  #   ports:
  #     - "80:80"
  #   # labels:
  #   #   - traefik.enable=true
  #   #   - traefik.http.routers.ei23-lan.rule=(Host(`192.168.178.2`) || Host(`raspberrypi`))
  #   #   - traefik.http.routers.ei23-lan.priority=1
  #   #   - traefik.http.routers.ei23-lan.entrypoints=lan
  #   restart: unless-stopped