site_name: Docs | Smart Home Server by ei23.de
nav:
  - Smart Home Server:
    - Los gehts: index.md
    - Installation & erster Start: start/install.md
    - Programme installieren & anpassen (Docker-Compose): start/docker-compose.md
    - ei23 Dashboard anpassen: start/ei23-dashboard.md
    - Backup & Restore: start/backuprestore.md
    - Häufige Fragen (FAQ): start/faq.md
    - Weitere Fragen?: 'https://ei23.de/donate'
  - Programme:
    - Home Assinstant: software/homeassistant.md
    - NodeRED: software/nodered.md
    - Traefik: software/traefik.md
    - WireguardVPN: software/wireguard.md
    - Nextcloud: software/nextcloud.md
    - Vaultwarden/Bitwarden: software/vaultwarden.md
    - ESPHome: software/esphome.md
    - PaperlessNGX: software/paperlessngx.md
    - MQTT-Explorer: software/mqttexplorer.md
    - Logitech-Media-Server: software/lms.md
    - Grafana: software/grafana.md
    - InfluxDB: software/influx.md
    - VSCode: software/vscode.md
  - Hardware:
    - Struktur: hardware/structure.md
    - Server: hardware/server.md
    - Edge Devices: hardware/edge-devices.md
  - Empfehlungen:
    - Akzeptanz der Mitbewohner: recommendations/acceptance.md
    - Absicherung: recommendations/security.md
    - Fernzugriff: recommendations/remote-access.md


theme:
  name: material
  language: de
  logo: media/ei23.svg
  favicon: media/favicon.png
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
  font:
    text: Barlow
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css
#   - stylesheets/codehilite.css

extra_javascript:
  - js/matomo.js

extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://ei23.de'
    - icon: fontawesome/brands/youtube
      link: 'https://youtube.com/ei23-de'
    - icon: fontawesome/brands/github
      link: 'https://github.com/ei23com/diy-smart-home'
    - icon: fontawesome/brands/reddit
      link: 'https://www.reddit.com/r/ei23/'
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/g88dNZq2'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/ei23de'