site_name: Docs | SmartHome-Server ei23.de
nav:
  - Start:
    - Startseite: index.md
    - Beispiel Seite: sample.md
  - Weitere Anleitungen:
    - Beispiel Seite 1: sample.md
    - Beispiel Seite 2: sample.md
    - Beispiel Seite 3: sample.md

theme:
  name: material
  language: de
  logo: media/ei23.svg
  favicon: media/favicon.png
  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
  font: 
    text: Karla
    code: Roboto Mono

extra_css:
  - stylesheets/extra.css

plugins:
  - privacy
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - offline

extra:
  social:
    - icon: fontawesome/solid/globe
      link: 'https://ei23.de'
    - icon: fontawesome/brands/youtube
      link: 'https://youtube.com/ei23-de'
    - icon: fontawesome/brands/github
      link: 'https://github.com/ei23com/diy-smart-home'
    - icon: fontawesome/brands/discord
      link: 'https://ei23.de/discord'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/ei23de'